version: '2'
services:
    smartinvestplus-mongodb:
        container_name: smartinvestplus-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/smartinvestplus/mongodb/:/data/db/
