version: '2'
services:
    smartinvestplus-mongodb:
        container_name: smartinvestplus-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        command: mongos --configdb smartinvestplus-mongodb-config
    smartinvestplus-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    smartinvestplus-mongodb-config:
        image: mongo:3.3.5
        container_name: smartinvestplus-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
